-- ============================================================
-- 045_reference_sequence_grants.sql
--
-- ACQ- and NSC-INV- references are generated by plain SQL functions used as
-- column defaults. A column default runs as whoever is inserting, not as the
-- function's owner, so both need USAGE on the sequence behind them. Without
-- it, creating an acquisition or issuing a proposal fails with
-- "permission denied for sequence".
--
-- contributor_id_seq is not affected: it is only ever reached through
-- assign_contributor_id(), which is SECURITY DEFINER and therefore runs as the
-- owner. Granted here anyway so the three behave alike.
-- ============================================================

GRANT USAGE, SELECT ON SEQUENCE public.acquisition_ref_seq TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.proposal_ref_seq TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.contributor_id_seq TO authenticated, service_role;

NOTIFY pgrst, 'reload schema';
